### PR TITLE
Feature/auth param

### PR DESCRIPTION
**Pull request by SchenkerRolf**

### CODE REVIEW

**Comment by shaenzi** [comment]
I get a different number of observations in the result... though this has more to do with the data than with the query

**Comment by SchenkerRolf** [comment]
> I get a different number of observations in the result... though this has more to do with the data than with the query

That is correct, the data changes over time.

**Comment by shaenzi** [comment]
Please adjust:

- [x] make sure that all functions that could be called from the outside 
    - have an auth parameter as an input
    - this auth parameter is passed to the appropriate function 
    - the auth parameter is documented
- [x] format better (see chat, uploading images does not work)
    - make all other, non-format changes
    - commit
    - use e.g. formatR::tidy_dir(path = ..., indent = 2) or styler::style_package or adjust manually

question: have you tried the authentication query from an rmarkdown?

**Comment by shaenzi** [comment]
an additional nice-to-have: throw a reasonable/understandable error based on the http error messages (e.g. authentication required)

**Comment by shaenzi** [comment]
added the missing auth parameters. in our ad-hoc tests, we only test the `sparql2df` function, but we should also test `sparql2list` and `eng_sparql`
--> @SchenkerRolf?

**Pull request merged**
